server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_manager
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "LJTkxABrk70sdc3BKO1+Y1MC8bPwHpmJXZKlDS+ndxiOL3cq30ifLJ7JVtNsLVxd"

